import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import RightBar from "@/components/rightbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "400", "600", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"h-screen w-screen grid grid-cols-12 overflow-hidden"}
        style={poppins.style}
      >
        <Sidebar />
        {children}
        <RightBar />
      </body>
    </html>
  );
}
